version: "2.1"
services:
  db: 
    image: mysql:5.7
    container_name: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    environment: 
      MYSQL_ROOT_PASSWORD: '123'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - sqldata:/var/lib/mysql
      
    healthcheck:
        test: "/usr/bin/mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
        interval: 17s
        timeout: 500s
        retries: 120
  app:
    image: 940900938199.dkr.ecr.us-east-2.amazonaws.com/lavagna
    container_name: app
    volumes: 
      - staticfolder:/app/webapp
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfolder:/usr/share/nginx/html/static/webapp
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    image: app_docs
    ports:
      - "8081:45001"
        
volumes:
  sqldata:
  staticfolder:
